"""initial schema

Revision ID: b54ad50b7886
Revises: 
Create Date: 2026-09-15 10:45:49.176865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54ad50b7886'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_scope'), 'analytics_snapshots', ['scope'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_snapshot_date'), 'analytics_snapshots', ['snapshot_date'], unique=False)
    op.create_table('clinics',
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('doctors_count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_hours', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_city'), 'clinics', ['city'], unique=False)
    op.create_index(op.f('ix_clinics_name'), 'clinics', ['name'], unique=False)
    op.create_table('diagnostic_labs',
    sa.Column('tests_offered', sa.Text(), nullable=True),
    sa.Column('accreditation', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_hours', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_labs_city'), 'diagnostic_labs', ['city'], unique=False)
    op.create_index(op.f('ix_diagnostic_labs_name'), 'diagnostic_labs', ['name'], unique=False)
    op.create_table('healthcare_services',
    sa.Column('facility_type', sa.String(length=30), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_services_facility_id'), 'healthcare_services', ['facility_id'], unique=False)
    op.create_index(op.f('ix_healthcare_services_facility_type'), 'healthcare_services', ['facility_type'], unique=False)
    op.create_table('hospitals',
    sa.Column('total_beds', sa.Integer(), nullable=True),
    sa.Column('available_beds', sa.Integer(), nullable=True),
    sa.Column('icu_beds', sa.Integer(), nullable=True),
    sa.Column('available_icu_beds', sa.Integer(), nullable=True),
    sa.Column('emergency_capacity', sa.Integer(), nullable=True),
    sa.Column('has_emergency', sa.Boolean(), nullable=False),
    sa.Column('departments', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_hours', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('pharmacies',
    sa.Column('has_delivery', sa.Boolean(), nullable=False),
    sa.Column('license_number', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('opening_hours', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_city'), 'pharmacies', ['city'], unique=False)
    op.create_index(op.f('ix_pharmacies_name'), 'pharmacies', ['name'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'DOCTOR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SUSPENDED', 'REJECTED', 'DISABLED', name='user_status'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('ai_predictions',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_interval_low', sa.Float(), nullable=True),
    sa.Column('confidence_interval_high', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_patient_id'), 'ai_predictions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_predictions_prediction_type'), 'ai_predictions', ['prediction_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('diet_plans',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('bmr', sa.Float(), nullable=True),
    sa.Column('tdee', sa.Float(), nullable=True),
    sa.Column('calorie_target', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('water_liters', sa.Float(), nullable=True),
    sa.Column('breakfast', sa.Text(), nullable=True),
    sa.Column('lunch', sa.Text(), nullable=True),
    sa.Column('dinner', sa.Text(), nullable=True),
    sa.Column('snacks', sa.Text(), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('dietary_preference', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_plans_patient_id'), 'diet_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_diet_plans_plan_date'), 'diet_plans', ['plan_date'], unique=False)
    op.create_table('doctor_applications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=False),
    sa.Column('qualification', sa.String(length=300), nullable=False),
    sa.Column('medical_registration_number', sa.String(length=100), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('hospital', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('consultation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Doctor registration/approval workflow'
    )
    op.create_index(op.f('ix_doctor_applications_medical_registration_number'), 'doctor_applications', ['medical_registration_number'], unique=True)
    op.create_index(op.f('ix_doctor_applications_specialization'), 'doctor_applications', ['specialization'], unique=False)
    op.create_index(op.f('ix_doctor_applications_status'), 'doctor_applications', ['status'], unique=False)
    op.create_index(op.f('ix_doctor_applications_user_id'), 'doctor_applications', ['user_id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=False),
    sa.Column('qualification', sa.String(length=300), nullable=False),
    sa.Column('medical_registration_number', sa.String(length=100), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('hospital', sa.String(length=200), nullable=False),
    sa.Column('clinic_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('consultation_type', sa.String(length=50), nullable=False),
    sa.Column('languages', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('online_consultation_enabled', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_profiles_medical_registration_number'), 'doctor_profiles', ['medical_registration_number'], unique=True)
    op.create_index(op.f('ix_doctor_profiles_specialization'), 'doctor_profiles', ['specialization'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    op.create_table('exercise_plans',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('plan_start', sa.Date(), nullable=False),
    sa.Column('fitness_level', sa.String(length=30), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('weekly_plan', sa.Text(), nullable=True),
    sa.Column('medical_restrictions', sa.Text(), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_plans_patient_id'), 'exercise_plans', ['patient_id'], unique=False)
    op.create_table('health_scores',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('previous_score', sa.Integer(), nullable=True),
    sa.Column('factors_improving', sa.Text(), nullable=True),
    sa.Column('factors_reducing', sa.Text(), nullable=True),
    sa.Column('breakdown', sa.Text(), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_scores_patient_id'), 'health_scores', ['patient_id'], unique=False)
    op.create_index(op.f('ix_health_scores_recorded_date'), 'health_scores', ['recorded_date'], unique=False)
    op.create_table('health_trends',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_trends_patient_id'), 'health_trends', ['patient_id'], unique=False)
    op.create_table('image_analyses',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=40), nullable=False),
    sa.Column('prediction_label', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('class_probabilities', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=False),
    sa.Column('grad_cam_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_analyses_modality'), 'image_analyses', ['modality'], unique=False)
    op.create_index(op.f('ix_image_analyses_patient_id'), 'image_analyses', ['patient_id'], unique=False)
    op.create_table('mental_wellness',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('journal_text', sa.Text(), nullable=True),
    sa.Column('breathing_session', sa.Text(), nullable=True),
    sa.Column('meditation_minutes', sa.Integer(), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mental_wellness_entry_type'), 'mental_wellness', ['entry_type'], unique=False)
    op.create_index(op.f('ix_mental_wellness_patient_id'), 'mental_wellness', ['patient_id'], unique=False)
    op.create_index(op.f('ix_mental_wellness_recorded_date'), 'mental_wellness', ['recorded_date'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('family_history', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_alt_phone', sa.String(length=20), nullable=True),
    sa.Column('activity_level', sa.String(length=30), nullable=True),
    sa.Column('dietary_preference', sa.String(length=30), nullable=True),
    sa.Column('health_goal', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_user_id'), 'patient_profiles', ['user_id'], unique=True)
    op.create_table('preventive_reminders',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('frequency_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preventive_reminders_due_date'), 'preventive_reminders', ['due_date'], unique=False)
    op.create_index(op.f('ix_preventive_reminders_patient_id'), 'preventive_reminders', ['patient_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_percentage', sa.Float(), nullable=False),
    sa.Column('factors', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_condition_type'), 'risk_assessments', ['condition_type'], unique=False)
    op.create_index(op.f('ix_risk_assessments_patient_id'), 'risk_assessments', ['patient_id'], unique=False)
    op.create_table('symptom_sessions',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('selected_symptoms', sa.Text(), nullable=False),
    sa.Column('symptoms_text', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_sessions_patient_id'), 'symptom_sessions', ['patient_id'], unique=False)
    op.create_table('ai_explanations',
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=True),
    sa.Column('image_analysis_id', sa.Integer(), nullable=True),
    sa.Column('explanation_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visual_key', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_analysis_id'], ['image_analyses.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['ai_predictions.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_explanations_image_analysis_id'), 'ai_explanations', ['image_analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_explanations_prediction_id'), 'ai_explanations', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_ai_explanations_risk_assessment_id'), 'ai_explanations', ['risk_assessment_id'], unique=False)
    op.create_table('doctor_availability',
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Weekly recurring availability with block-out slots'
    )
    op.create_index(op.f('ix_doctor_availability_doctor_profile_id'), 'doctor_availability', ['doctor_profile_id'], unique=False)
    op.create_table('doctor_qualifications',
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('year_completed', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_qualifications_doctor_profile_id'), 'doctor_qualifications', ['doctor_profile_id'], unique=False)
    op.create_table('doctor_specialties',
    sa.Column('doctor_profile_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_specialties_doctor_profile_id'), 'doctor_specialties', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_doctor_specialties_specialty'), 'doctor_specialties', ['specialty'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_patient_profile_id'), 'emergency_contacts', ['patient_profile_id'], unique=False)
    op.create_table('family_profiles',
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_profiles_patient_profile_id'), 'family_profiles', ['patient_profile_id'], unique=False)
    op.create_table('symptom_results',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('recommended_specialty', sa.String(length=120), nullable=True),
    sa.Column('emergency_flag', sa.Boolean(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['symptom_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_results_condition_name'), 'symptom_results', ['condition_name'], unique=False)
    op.create_index(op.f('ix_symptom_results_session_id'), 'symptom_results', ['session_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('family_profile_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('consultation_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('symptoms_summary', sa.Text(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_policy_ack', sa.Boolean(), nullable=False),
    sa.Column('video_room_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_family_profile_id'), 'appointments', ['family_profile_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_date'), 'appointments', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('health_metrics',
    sa.Column('patient_profile_id', sa.Integer(), nullable=True),
    sa.Column('family_profile_id', sa.Integer(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('systolic', sa.Float(), nullable=True),
    sa.Column('diastolic', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metrics_family_profile_id'), 'health_metrics', ['family_profile_id'], unique=False)
    op.create_index(op.f('ix_health_metrics_metric_type'), 'health_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_health_metrics_patient_profile_id'), 'health_metrics', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_health_metrics_recorded_date'), 'health_metrics', ['recorded_date'], unique=False)
    op.create_table('medical_histories',
    sa.Column('patient_profile_id', sa.Integer(), nullable=True),
    sa.Column('family_profile_id', sa.Integer(), nullable=True),
    sa.Column('condition_name', sa.String(length=200), nullable=False),
    sa.Column('diagnosed_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_histories_family_profile_id'), 'medical_histories', ['family_profile_id'], unique=False)
    op.create_index(op.f('ix_medical_histories_patient_profile_id'), 'medical_histories', ['patient_profile_id'], unique=False)
    op.create_table('medical_reports',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('family_profile_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_driver', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_reports_category'), 'medical_reports', ['category'], unique=False)
    op.create_index(op.f('ix_medical_reports_condition'), 'medical_reports', ['condition'], unique=False)
    op.create_index(op.f('ix_medical_reports_family_profile_id'), 'medical_reports', ['family_profile_id'], unique=False)
    op.create_index(op.f('ix_medical_reports_patient_id'), 'medical_reports', ['patient_id'], unique=False)
    op.create_table('medications',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('family_profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('frequency_detail', sa.String(length=200), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('refill_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('refill_threshold_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('prescribed_by', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('adherence_rate', sa.Float(), nullable=True),
    sa.Column('intake_log', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_family_profile_id'), 'medications', ['family_profile_id'], unique=False)
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_table('consultations',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('clinical_impression', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('vital_signs', sa.Text(), nullable=True),
    sa.Column('recommended_tests', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('follow_up_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_appointment_id'), 'consultations', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('refill_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_consultation_id'), 'prescriptions', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('health_timeline',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('family_profile_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_timeline_event_date'), 'health_timeline', ['event_date'], unique=False)
    op.create_index(op.f('ix_health_timeline_event_type'), 'health_timeline', ['event_type'], unique=False)
    op.create_index(op.f('ix_health_timeline_family_profile_id'), 'health_timeline', ['family_profile_id'], unique=False)
    op.create_index(op.f('ix_health_timeline_patient_id'), 'health_timeline', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_timeline_patient_id'), table_name='health_timeline')
    op.drop_index(op.f('ix_health_timeline_family_profile_id'), table_name='health_timeline')
    op.drop_index(op.f('ix_health_timeline_event_type'), table_name='health_timeline')
    op.drop_index(op.f('ix_health_timeline_event_date'), table_name='health_timeline')
    op.drop_table('health_timeline')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_consultation_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_doctor_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_appointment_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_family_profile_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medical_reports_patient_id'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_family_profile_id'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_condition'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_category'), table_name='medical_reports')
    op.drop_table('medical_reports')
    op.drop_index(op.f('ix_medical_histories_patient_profile_id'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_family_profile_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_health_metrics_recorded_date'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_patient_profile_id'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_metric_type'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_family_profile_id'), table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_family_profile_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_symptom_results_session_id'), table_name='symptom_results')
    op.drop_index(op.f('ix_symptom_results_condition_name'), table_name='symptom_results')
    op.drop_table('symptom_results')
    op.drop_index(op.f('ix_family_profiles_patient_profile_id'), table_name='family_profiles')
    op.drop_table('family_profiles')
    op.drop_index(op.f('ix_emergency_contacts_patient_profile_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_doctor_specialties_specialty'), table_name='doctor_specialties')
    op.drop_index(op.f('ix_doctor_specialties_doctor_profile_id'), table_name='doctor_specialties')
    op.drop_table('doctor_specialties')
    op.drop_index(op.f('ix_doctor_qualifications_doctor_profile_id'), table_name='doctor_qualifications')
    op.drop_table('doctor_qualifications')
    op.drop_index(op.f('ix_doctor_availability_doctor_profile_id'), table_name='doctor_availability')
    op.drop_table('doctor_availability')
    op.drop_index(op.f('ix_ai_explanations_risk_assessment_id'), table_name='ai_explanations')
    op.drop_index(op.f('ix_ai_explanations_prediction_id'), table_name='ai_explanations')
    op.drop_index(op.f('ix_ai_explanations_image_analysis_id'), table_name='ai_explanations')
    op.drop_table('ai_explanations')
    op.drop_index(op.f('ix_symptom_sessions_patient_id'), table_name='symptom_sessions')
    op.drop_table('symptom_sessions')
    op.drop_index(op.f('ix_risk_assessments_patient_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_condition_type'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_preventive_reminders_patient_id'), table_name='preventive_reminders')
    op.drop_index(op.f('ix_preventive_reminders_due_date'), table_name='preventive_reminders')
    op.drop_table('preventive_reminders')
    op.drop_index(op.f('ix_patient_profiles_user_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_mental_wellness_recorded_date'), table_name='mental_wellness')
    op.drop_index(op.f('ix_mental_wellness_patient_id'), table_name='mental_wellness')
    op.drop_index(op.f('ix_mental_wellness_entry_type'), table_name='mental_wellness')
    op.drop_table('mental_wellness')
    op.drop_index(op.f('ix_image_analyses_patient_id'), table_name='image_analyses')
    op.drop_index(op.f('ix_image_analyses_modality'), table_name='image_analyses')
    op.drop_table('image_analyses')
    op.drop_index(op.f('ix_health_trends_patient_id'), table_name='health_trends')
    op.drop_table('health_trends')
    op.drop_index(op.f('ix_health_scores_recorded_date'), table_name='health_scores')
    op.drop_index(op.f('ix_health_scores_patient_id'), table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index(op.f('ix_exercise_plans_patient_id'), table_name='exercise_plans')
    op.drop_table('exercise_plans')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_specialization'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_medical_registration_number'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_doctor_applications_user_id'), table_name='doctor_applications')
    op.drop_index(op.f('ix_doctor_applications_status'), table_name='doctor_applications')
    op.drop_index(op.f('ix_doctor_applications_specialization'), table_name='doctor_applications')
    op.drop_index(op.f('ix_doctor_applications_medical_registration_number'), table_name='doctor_applications')
    op.drop_table('doctor_applications')
    op.drop_index(op.f('ix_diet_plans_plan_date'), table_name='diet_plans')
    op.drop_index(op.f('ix_diet_plans_patient_id'), table_name='diet_plans')
    op.drop_table('diet_plans')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_predictions_prediction_type'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_patient_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pharmacies_name'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_city'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_healthcare_services_facility_type'), table_name='healthcare_services')
    op.drop_index(op.f('ix_healthcare_services_facility_id'), table_name='healthcare_services')
    op.drop_table('healthcare_services')
    op.drop_index(op.f('ix_diagnostic_labs_name'), table_name='diagnostic_labs')
    op.drop_index(op.f('ix_diagnostic_labs_city'), table_name='diagnostic_labs')
    op.drop_table('diagnostic_labs')
    op.drop_index(op.f('ix_clinics_name'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_city'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_analytics_snapshots_snapshot_date'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_scope'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###